wip more

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -5,7 +5,7 @@ set -euo pipefail
 IFS=$'\n\t'
 
 print_help() {
-	cat <<EOF
+  cat <<EOF
 setup - Set up the Emacs environment by installing dependencies, downloading
         source, building, and installing.
 
@@ -39,253 +39,275 @@ EOF
 base="${EMACS_SETUP_BASE:-$HOME/.emacs.d/src}"
 
 required=(
-	autoconf
-	cmake
-	texinfo
-	libxml2
-	imagemagick
-	librsvg
-	gnutls
-	gnupg
-	jansson
-	cairo
-	libvterm
+  autoconf
+  cmake
+  texinfo
+  libxml2
+  imagemagick
+  librsvg
+  gnutls
+  gnupg
+  jansson
+  cairo
+  libvterm
 )
 
 required_mu4e=(
-	automake
-	libgpg-error
-	libtool
-	pkg-config
-	gettext
-	glib
-	gmime
-	xapian
-	guile
-	isync
+  automake
+  libgpg-error
+  libtool
+  pkg-config
+  gettext
+  glib
+  gmime
+  xapian
+  guile
+  isync
 )
 
 required_casks=(mactex)
 
 configure_opts=(
-	CFLAGS="-Ofast -march=native -pipe -falign-functions=64 -fomit-frame-pointer -funit-at-a-time -fforce-addr -mfpmath=sse -ffast-math -fno-finite-math-only -fstack-check -I/usr/local/opt/libxml2/include/libxml2"
-	LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
-	CPPFLAGS="-I/usr/local/opt/llvm/include"
-	PKG_CONFIG_PATH="PKG_CONFIG_PATH:/usr/local/opt/gnutls/lib/pkgconfig:/usr/local/opt/nettle/lib/pkgconfig:/usr/local/opt/libtasn1/lib/pkgconfig:/usr/local/opt/p11-kit/lib/pkgconfig:/usr/local/opt/imagemagick/lib/pkgconfig"
+  CFLAGS="-Ofast -march=native -pipe -falign-functions=64 -fomit-frame-pointer -funit-at-a-time -fforce-addr -mfpmath=sse -ffast-math -fno-finite-math-only -fstack-check -I/usr/local/opt/libxml2/include/libxml2"
+  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"
+  CPPFLAGS="-I/usr/local/opt/llvm/include"
+  PKG_CONFIG_PATH="PKG_CONFIG_PATH:/usr/local/opt/gnutls/lib/pkgconfig:/usr/local/opt/nettle/lib/pkgconfig:/usr/local/opt/libtasn1/lib/pkgconfig:/usr/local/opt/p11-kit/lib/pkgconfig:/usr/local/opt/imagemagick/lib/pkgconfig"
 )
 
 # The ctags bit is to rename the ctags binary so it doesn't conflict with an
 # existing, non-emacs ctags installation
 emacs_configure_opts=(
-	--config-cache
-	--without-pop
-	--with-ns
-	--disable-ns-self-contained
-	--with-cairo
-	# --with-imagemagick
-	--with-modules
-	--program-transform-name='s/^ctags$/ctags.emacs/'
-	"${configure_opts[@]}"
+  --config-cache
+  --without-pop
+  --with-ns
+  --disable-ns-self-contained
+  --with-cairo
+  # --with-imagemagick
+  --with-modules
+  --program-transform-name='s/^ctags$/ctags.emacs/'
+  "${configure_opts[@]}"
 )
 
 # Print the given arguments out in a nice heading
 heading() {
-	printf "\n\033[38;5;013m * %s  \033[0m  \n\n" "$*"
+  printf "\n\033[38;5;013m * %s  \033[0m  \n\n" "$*"
 }
 
 # Return exit code 0 if $1 is the same as any of the rest of the arguments
 contains() {
-	local e match="$1"
-	shift
-	for e in "$@"; do [ "$e" = "$match" ] && return 0; done
-	return 1
+  local e match="$1"
+  shift
+  for e in "$@"; do [ "$e" = "$match" ] && return 0; done
+  return 1
 }
 
 # Ensure the directory to which we will install Emacs exists and has the correct
 # permissions set.
 ensure_install_directory() {
-	local libexec=/usr/local/libexec/emacs
-	if [ ! -d $libexec ]; then
-		sudo mkdir -p $libexec
-		chown $USER $libexec
-	fi
+  local libexec=/usr/local/libexec/emacs
+  if [ ! -d $libexec ]; then
+    sudo mkdir -p $libexec
+    chown $USER $libexec
+  fi
 }
 
 # Ensure the given homebrew packages are installed and up to date
 # brew_ensure [ cask ] dep1 [ dep2 ] [ ... ]
 brew_ensure() {
-	local prefix required missing outdated upgrade
-	# Decide if we are operating on 'brew' or 'brew cask'
-	prefix="brew "
-	[ "$1" = "cask" ] && prefix="${prefix}cask " && shift
+  local prefix required missing outdated upgrade
+  # Decide if we are operating on 'brew' or 'brew cask'
+  prefix="brew "
+  [ "$1" = "cask" ] && prefix="${prefix}cask " && shift
 
-	# Get list of missing packages, install them
-	installed=($(eval $prefix list -1))
-	required=("$@")
-	for p in "${required[@]}"; do
-		contains "$p" "${installed[@]}" || missing+=("$p")
-	done
-	if [ -n "${missing[*]:-}" ]; then
-		echo "Installing packages: ${missing[*]}"
-		eval $prefix install "${missing[@]}"
-	fi
+  # Get list of missing packages, install them
+  installed=($(eval $prefix list -1))
+  required=("$@")
+  for p in "${required[@]}"; do
+    contains "$p" "${installed[@]}" || missing+=("$p")
+  done
+  if [ -n "${missing[*]:-}" ]; then
+    echo "Installing packages: ${missing[*]}"
+    eval $prefix install "${missing[@]}"
+  fi
 
-	# Get list of outdated packages, upgrade them
-	outdated="$(eval $prefix outdated | awk '{print $1}')"
-	upgrade=()
-	for p in "${required[@]}"; do
-		contains "$p" "${outdated[@]}" && upgrade+=("$p")
-	done
-	if [ -n "${upgrade[*]:-}" ]; then
-		echo "Upgrading packages: ${upgrade[*]}"
-		eval $prefix upgrade "${upgrade[@]}"
-	fi
+  # Get list of outdated packages, upgrade them
+  outdated="$(eval $prefix outdated | awk '{print $1}')"
+  upgrade=()
+  for p in "${required[@]}"; do
+    contains "$p" "${outdated[@]}" && upgrade+=("$p")
+  done
+  if [ -n "${upgrade[*]:-}" ]; then
+    echo "Upgrading packages: ${upgrade[*]}"
+    eval $prefix upgrade "${upgrade[@]}"
+  fi
 }
 
 # Print the number of CPU cores on the local machine
 how_many_cores() {
-	case "$(uname)" in
-	Darwin)
-		sysctl -n hw.ncpu
-		;;
-	Linux)
-		awk '/^processor/ {++n} END {print n}' /proc/cpuinfo
-		;;
-	esac
+  case "$(uname)" in
+  Darwin)
+    sysctl -n hw.ncpu
+    ;;
+  Linux)
+    awk '/^processor/ {++n} END {print n}' /proc/cpuinfo
+    ;;
+  esac
 }
 
 # Install Emacs dependencies
 deps_emacs() {
-	heading "Installing Dependencies for Emacs..."
+  heading "Installing Dependencies for Emacs..."
 
-	brew_ensure "${required[@]}"
-	brew_ensure cask "${required_casks[@]}"
-	brew install --HEAD universal-ctags/universal-ctags/universal-ctags
+  brew_ensure "${required[@]}"
+  brew_ensure cask "${required_casks[@]}"
+  brew install --HEAD universal-ctags/universal-ctags/universal-ctags
 
-	# Apparently gnutls is bottled now.
-	which gnutls || PATH="$(brew --prefix gnutls):$PATH"
+  # Apparently gnutls is bottled now.
+  which gnutls || PATH="$(brew --prefix gnutls):$PATH"
 }
 
 # Install Emacs dependencies
 deps_mu4e() {
-	heading "Installing Dependencies for mu4e..."
+  heading "Installing Dependencies for mu4e..."
 
-	brew_ensure "${required_mu4e[@]}"
+  brew_ensure "${required_mu4e[@]}"
 }
 
 deps() {
-	local target="$1"
-	case "$target" in
-	emacs) deps_emacs ;;
-	mu4e) deps_mu4e ;;
-	esac
+  local target="$1"
+  case "$target" in
+  emacs) deps_emacs ;;
+  mu4e) deps_mu4e ;;
+  esac
 }
 
 # Fetch the Emacs source repository
 fetch() {
-	local repo="$1"
-	local target="$2"
-	heading "Fetching source for $target..."
-	echo "Source directory will be $base/$target"
+  local url="$1"
+  local target="$2"
+  heading "Fetching source for $target..."
+  echo "Source directory will be $base/$target"
 
-	mkdir -p "$base"
-	pushd "$base"
+  mkdir -p "$base"
+  pushd "$base"
 
-	[ -d "$base/$target" ] || git clone "$repo" "$target"
-	pushd "$base/$target"
+  [ -d "$base/$target" ] || git clone "$url" "$target"
+  pushd "$base/$target"
 
-	git pull
+  git fetch
+  git checkout "$ref"
+  # git pull
 }
 
 # Build Emacs from source
 build_it() {
-	local target="$1"
-	shift
-	heading "Building $target..."
+  local target="$1"
+  shift
+  heading "Building $target..."
 
-	pushd "$base/$target"
+  pushd "$base/$target"
 
-	make distclean
-	./autogen.sh
-	./configure "$@"
-	make -j $make_jobs
+  make distclean
+  ./autogen.sh
+  ./configure "$@"
+  make -j $make_jobs
 
-	popd
+  popd
 }
 
 build() {
-	local target="$1"
-	case "$target" in
-	emacs) build_it "$target" "${emacs_configure_opts[@]}" ;;
-	mu4e) build_it "$target" "${configure_opts[@]}" ;;
-	esac
+  local target="$1"
+  case "$target" in
+  emacs) build_it "$target" "${emacs_configure_opts[@]}" ;;
+  mu4e) build_it "$target" "${configure_opts[@]}" ;;
+  esac
 }
 
 # Install Emacs from the build directory
 install_emacs() {
-	heading "Installing Emacs..."
+  heading "Installing Emacs..."
 
-	ensure_install_directory
+  ensure_install_directory
 
-	pushd "$base/$target"
+  pushd "$base/$target"
 
-	# Even though we move the binary ourselves, we still need to install to get the
-	# Emacs Lisp and C source files in the right place.
-	make -j $make_jobs install
-	rm -rf "$HOME/Applications/Emacs.app"
-	mv nextstep/Emacs.app "$HOME/Applications/"
+  # Even though we move the binary ourselves, we still need to install to get
+  # the Emacs Lisp and C source files in the right place.
+  make -j $make_jobs install
+  rm -rf "$HOME/Applications/Emacs.app"
+  mv nextstep/Emacs.app "$HOME/Applications/"
 
-	popd
+  popd
 }
 
 install_mu4e() {
-	heading "Installing Emacs..."
+  heading "Installing Emacs..."
 
-	pushd "$base/$target"
+  pushd "$base/$target"
 
-	make -j $make_jobs install
+  make -j $make_jobs install
 }
 
 install() {
-	local target="$1"
-	case "$target" in
-	emacs) install_emacs "$target" ;;
-	mu4e) install_mu4e "$target" ;;
-	esac
+  local target="$1"
+  case "$target" in
+  emacs) install_emacs "$target" ;;
+  mu4e) install_mu4e "$target" ;;
+  esac
 }
 
+
+# Defaults
 make_jobs=$((2 * $(how_many_cores)))
+ref="master"
+task="all"
+target="emacs"
+url=""
 
-target="${1:-emacs}"
-task="${2:-all}"
+while getopts ":r:s:t:u:" opt; do
+  case "$opt" in
+    r) ref="${OPTARG}" ;;
+    s) task="${OPTARG}" ;;
+    t) target="${OPTARG}" ;;
+    u) url="${OPTARG}" ;;
+    *) print_help
+       exit 2
+       ;;
+  esac
+done
+shift $(expr $OPTIND - 1)
+OPTIND=1
 
+
+if [ -z "$url" ] ; then
 case "$target" in
 emacs)
-	repo="${2:-https://git.savannah.gnu.org/git/emacs.git}"
-	;;
+  url="https://git.savannah.gnu.org/git/emacs.git"
+  ;;
 mu4e)
-	repo="${2:-https://github.com/djcb/mu.git}"
-	;;
+  url="https://github.com/djcb/mu.git"
+  ;;
 esac
+fi
 
 case "$task" in
 deps)
-	deps
-	;;
+  deps
+  ;;
 fetch)
-	fetch "$repo" "$target"
-	;;
+  fetch "$url" "$target"
+  ;;
 build)
-	build "$target"
-	;;
+  build "$target"
+  ;;
 mu4e)
-	fetch
-	;;
+  fetch
+  ;;
 -h | --help | h*) print_help ;;
 all)
-	deps "$target"
-	fetch "$repo" "$target"
-	build "$target"
-	install "$target"
-	;;
+  deps "$target"
+  fetch "$url" "$target"
+  build "$target"
+  install "$target"
+  ;;
 esac
